version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - misspell
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/andmetoo/mailcatcher
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
